name: Package and Release APKs

on:
  push:
    branches:
      - main 

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Password Protected ZIP
        run: |
          # -P 后跟密码，-j 表示不包含目录结构
          zip -P 1024@ -j output.zip AutoJS.fake.latest.apk KernelSU_v1.0.1.apk MT2.26.4.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: 加密APK存档-${{ github.run_number }}
          body: "已加密的APK集合文件，解压密码为: 1024@"
          files: output.zip
          draft: false
          prerelease: false
